import Head from 'next/head';

import { useEffect, useState } from 'react';

// UI components
import Header from '../components/common/Header';
import SideBarPopOut from '../components/common/SideBarPopOut';
import SideBar from '../components/common/SideBar';
import HomeDashboard from '../components/dashboard/HomeDashboard';

export default function Home() {
  const [currentMenu, setCurrentMenu] = useState('home');

  useEffect(() => {
    console.log(currentMenu);
  }, [currentMenu]);

  return (
    <div>
      <Head>
        <title>Legible Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen w-screen overflow-hidden relative">
        <Header />
        <SideBarPopOut />

        <section className="w-full h-full flex">
          <SideBar setCurrentMenu={setCurrentMenu} />
          <section className="w-full h-full">
            {currentMenu === 'home' && <HomeDashboard />}
          </section>
        </section>
      </main>
    </div>
  );
}
